module.exports.basicCards = {  
    basic1 : {img : "Warrior1", name : "Warrior", atk : 1, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Soldier", style : "passive", cost : 0, desc : "A brave soldier for your army",},
    basic2 : {img : "Warrior2", name : "Warrior", atk : 1, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Soldier", style : "passive", cost : 0, desc : "A brave soldier for your army",},
    basic3 : {img : "Warrior3", name : "Warrior", atk : 1, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Soldier", style : "passive", cost : 0, desc : "A brave soldier for your army",},
    basic4 : {img : "Warrior4", name : "Warrior", atk : 1, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Soldier", style : "passive", cost : 0, desc : "A brave soldier for your army",},
    basic5 : {img : "Archer1", name : "Archer", atk : 1, hp : 1, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Ranged", style : "passive", cost : 0, desc : "All attacks are ranged",},
    basic6 : {img : "Archer2", name : "Archer", atk : 1, hp : 1, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Ranged", style : "passive", cost : 0, desc : "All attacks are ranged",},
    basic7 : {img : "Horseman1", name : "Horseman", atk : 2, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Charge", style : "bolt", cost : 0, desc : "Can always attack first",},
    basic8 : {img : "Horseman2", name : "Horseman", atk : 2, hp : 2, connect : 2, red : 0, green : 0, blue : 0, type : "basic", ability : "Charge", style : "bolt", cost : 0, desc : "Can always attack first",},
};

module.exports.basicCards2 = {
    basic1 : {img : "Helmet1", name : "Helmet", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A trusty helmet",},
    basic2 : {img : "Helmet2", name : "Helmet", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A trusty helmet",},
    basic3 : {img : "Shield1", name : "Shield", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A tough shield",},
    basic4 : {img : "Shield2", name : "Shield", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A tough shield",},
    basic5 : {img : "Sword1", name : "Sword", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A sharp sword",},
    basic6 : {img : "Sword2", name : "Sword", atk : 1, hp : 2, connect : 1, red : 0, green : 0, blue : 0, type : "basic", ability : "Equipment", style : "passive", cost : 0, desc : "A sharp sword",},
};

module.exports.warCards = {
    war1 : {img : "Leuctra", ability : "The Battle of Leuctra", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war2 : {img : "PeloponnesianWar", ability : "The Peloponnesian War", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war3 : {img : "TrojanWar", ability : "The Trojan War", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war4 : {img : "Thermopylae", ability : "The Battle of Thermopylae", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war5 : {img : "Salamis", ability : "The Battle of Salamis", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war6 : {img : "Marathon", ability : "The Battle of Marathon", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war7 : {img : "Syracuse", ability : "The Battle of Syracuse", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
    war8 : {img : "Titanomachy", ability : "The Titanomachy", atk : 1, hp : 2, connect : 0, red : 0, green : 0, blue : 0, type : "battle", name : "Battle", style : "passive", cost : 0, desc : "",},
}

module.exports.heroes = {
// Heroes
    hero1 : {img : "Heracles", name : "Heracles", atk : 6, hp : 9, connect : 4, red : 3, green : 1, blue : 0, type : "hero", ability : "Strength of the Gods", style : "bolt", cost : 3, desc : "Deal +3 dmg on first attack",},
    hero2 : {img : "Perseus", name : "Perseus", atk : 4, hp : 8, connect : 4, red : 1, green : 2, blue : 1, type : "hero", ability : "Medusa's Gaze", style : "bolt", cost : 3, desc : "Stun 2 Enemies",},
    hero3 : {img : "Achilles", name : "Achilles", atk : 5, hp : 9, connect : 4, red : 4, green : 0, blue : 0, type : "hero", ability : "Quelling Blade", style : "passive", cost : 3, desc : "Deal +2 dmg against units who have lost hp",},
    hero4 : {img : "Jason", name : "Jason", atk : 3, hp : 5, connect : 4, red : 1, green : 1, blue : 2, type : "hero", ability : "Heroic Connections", style : "passive", cost : 3, desc : "Heroes cost 1 less card to recruit",},
    hero5 : {img : "Odysseus", name : "Odysseus", atk : 4, hp : 8, connect : 4, red : 0, green : 1, blue : 3, type : "hero", ability : "Set Trap", style : "bolt", cost : 3, desc : "Stun or deal 2 dmg to an enemy or swap 2 enemy cards",},
    hero6 : {img : "Diomedes", name : "Diomedes", atk : 5, hp : 8, connect : 4, red : 2, green : 2, blue : 0, type : "hero", ability : "Battle Hunger", style : "passive", cost : 3, desc : "Diomedes takes -1 dmg from non heroes",},
    hero7 : {img : "Ajax", name : "Ajax", atk : 5, hp : 10, connect : 4, red : 3, green : 1, blue : 0, type : "hero", ability : "Bulwark", style : "passive", cost : 3, desc : "Connected cards receive one less dmg when attacked",},
    hero8 : {img : "Minos", name : "Minos", atk : 3, hp : 6, connect : 3, red : 3, green : 0, blue : 0, type : "hero", ability : "Royal Hatred", style : "passive", cost : 2, desc : "Deal +2 dmg to blue cards",},
    hero9 : {img : "Nestor", name : "Nestor", atk : 2, hp : 7, connect : 3, red : 0, green : 0, blue : 3, type : "hero", ability : "Age-old Wisdom", style : "bolt", cost : 2, desc : "Switch 2 enemy cards and heal 2 dmg on an ally",},
    hero10 : {img : "Atalanta", name : "Atalanta", atk : 4, hp : 4, connect : 3, red : 0, green : 3, blue : 0, type : "hero", ability : "Swift-footed Archer", style : "passive", cost : 2, desc : "Attacks are ranged and can always attack first",},
    hero11 : {img : "Medea", name : "Medea", atk : 1, hp : 5, connect : 3, red : 1, green : 0, blue : 2, type : "hero", ability : "Nullify", style : "bolt", cost : 2, desc : "Stun an enemy and deal 2 dmg",},
    hero12 : {img : "Ariadne", name : "Ariadne", atk : 1, hp : 4, connect : 2, red : 0, green : 1, blue : 1, type : "hero", ability : "Loyal Companion", style : "bolt", cost : 1, desc : "Can heal two dmg on an ally",},
    hero13 : {img : "Hippolyta", name : "Hippolyta", atk : 5, hp : 5, connect : 4, red : 0, green : 4, blue : 0, type : "hero", ability : "Master Huntress", style : "passive", cost : 3, desc : "Attacks are ranged and deal +1 dmg",},
    hero14 : {img : "Penelope", name : "Penelope", atk : 1, hp : 4, connect : 2, red : 0, green : 0, blue : 2, type : "hero", ability : "Faithful", style : "bolt", cost : 1, desc : "Can heal two dmg on an ally",},
    hero15 : {img : "Meleager", name : "Meleager", atk : 4, hp : 5, connect : 3, red : 2, green : 1, blue : 0, type : "hero", ability : "Hunter's Instinct", style : "passive", cost : 2, desc : "Takes -1 dmg from units with less attack than him",},
    hero16 : {img : "Bellerophon", name : "Bellerophon", atk : 4, hp : 4, connect : 3, red : 1, green : 2, blue : 0, type : "hero", ability : "Monster Hunter", style : "passive", cost : 2, desc : "Immune to dmg from monsters",},
    hero17 : {img : "Daedalus", name : "Daedalus", atk : 1, hp : 4, connect : 3, red : 0, green : 0, blue : 3, type : "hero", ability : "Master Craftsman", style : "bolt", cost : 2, desc : "Switch two enemy cards",},    
    hero18 : {img : "Pandora", name : "Pandora", atk : 1, hp : 3, connect : 2, red : 0, green : 1, blue : 1, type : "hero", ability : "Chaotic Curiosity", style : "bolt", cost : 1, desc : "Roll dice : if 3<X deal +X/2 dmg else take X dmg",}, 
    hero19 : {img : "Cassandra", name : "Cassandra", atk : 1, hp : 3, connect : 2, red : 0, green : 0, blue : 2, type : "hero", ability : "Cursed Prophecy", style : "passive", cost : 1, desc : "Prevent an enemy ability, then die",}, 
    hero20 : {img : "Neoptolemus", name : "Neoptolemus", atk : 4, hp : 5, connect : 3, red : 3, green : 0, blue : 0, type : "hero", ability : "His Father's Rage", style : "passive", cost : 2, desc : "Deal +2 dmg to blue cards",}, 
    hero21 : {img : "Clytemnestra", name : "Clytemnestra", atk : 2, hp : 3, connect : 2, red : 2, green : 0, blue : 0, type : "hero", ability : "Hero Slayer", style : "passive", cost : 1, desc : "Deal +5 dmg to heroes",}, 
    hero22 : {img : "Orpheus", name : "Orpheus", atk : 1, hp : 4, connect : 2, red : 0, green : 1, blue : 1, type : "hero", ability : "Master of Music", style : "bolt", cost : 1, desc : "Heal all units by one",}, 
    hero23 : {img : "Patroclus", name : "Patroclus", atk : 3, hp : 7, connect : 3, red : 2, green : 0, blue : 1, type : "hero", ability : "Brotherly Love", style : "passive", cost : 2, desc : "Take dmg in place of another",},
    hero25 : {img : "Theseus", name : "Theseus", atk : 5, hp : 8, connect : 4, red : 1, green : 2, blue : 1, type : "hero", ability : "Liberator of Athens", style : "passive", cost : 3, desc : "Reduces dmg from incoming attacks by 1",},
    hero26 : {img : "Alcibiades", name : "Alcibiades", atk : 3, hp : 2, connect : 2, red : 1, green : 0, blue : 1, type : "hero", ability : "Disloyal", style : "passive", cost : 1, desc : "On first death transfer to the killer's team with 1 health",},
    hero27 : {img : "Hippolytus", name : "Hippolytus", atk : 2, hp : 4, connect : 2, red : 0, green : 2, blue : 0, type : "hero", ability : "Call of the Wild", style : "passive", cost : 1, desc : "Monsters cost -1 card to recruit",},
    hero28 : {img : "Cecrops", name : "Cecrops", atk : 1, hp : 4, connect : 2, red : 0, green : 0, blue : 2, type : "hero", ability : "Experienced Ruler", style : "bolt", cost : 2, desc : "Draw a basic card",},
    hero29 : {img : "Menelaus", name : "Menelaus", atk : 5, hp : 7, connect : 4, red : 3, green : 1, blue : 0, type : "hero", ability : "Duelist", style : "bolt", cost : 3, desc : "Attack an enemy until one dies, take -1 dmg per attack",},
    hero30 : {img : "Helen", name : "Helen", atk : 1, hp : 5, connect : 3, red : 1, green : 1, blue : 1, type : "hero", ability : "Casus Belli", style : "bolt", cost : 1, desc : "Place in the enemy army, all surrounding cards take +1 dmg",},
    hero31 : {img : "Brasidas", name : "Brasidas", atk : 3, hp : 6, connect : 3, red : 2, green : 0, blue : 1, type : "hero", ability : "Master Tactician", style : "passive", cost : 2, desc : "You can rearrange your army at any point in a battle",},
    hero32 : {img : "Orestes", name : "Orestes", atk : 3, hp : 5, connect : 3, red : 3, green : 0, blue : 0, type : "hero", ability : "Vengeful", style : "passive", cost : 2, desc : "Everytime Orestes is attacked, he deals x2 his attack back",},
    hero33 : {img : "Oedipus", name : "Oedipus", atk : 3, hp : 5, connect : 3, red : 0, green : 2, blue : 1, type : "hero", ability : "Ill-Fated", style : "passive", cost : 2, desc : "Deal +2 dmg to red cards but -2 dmg to blue",},
    hero34 : {img : "Tiresias", name : "Tiresias", atk : 0, hp : 4, connect : 2, red : 0, green : 0, blue : 2, type : "hero", ability : "Foresight", style : "passive", cost : 1, desc : "Prevent an enemy ability, then die",},
    hero35 : {img : "Hector", name : "Hector", atk : 5, hp : 8, connect : 4, red : 2, green : 1, blue : 1, type : "hero", ability : "Sweeping Attack", style : "bolt", cost : 3, desc : "Deal 1 dmg to all connected cards, 2 if they are green",},
    hero36 : {img : "Paris", name : "Paris", atk : 4, hp : 5, connect : 3, red : 2, green : 1, blue : 0, type : "hero", ability : "Master Archer", style : "passive", cost : 2, desc : "Attacks are ranged, deal +1 to red cards",},
    hero37 : {img : "Hecuba", name : "Hecuba", atk : 1, hp : 4, connect : 3, red : 0, green : 1, blue : 2, type : "hero", ability : "Royal Influence", style : "bolt", cost : 2, desc : "Can heal 2 dmg on an ally",},
    hero38 : {img : "Peleus", name : "Peleus", atk : 3, hp : 4, connect : 3, red : 0, green : 2, blue : 1, type : "hero", ability : "Divine favour", style : "passive", cost : 3, desc : "Reduces the cost of recruiting gods by 1 card",},
// Gods
    god1 : {img : "Dionysus", name : "Dionysus", atk : 4, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Festival Rites", style : "passive", cost : 5, desc : "All soldiers have +1 atk and take -1 dmg",},
    god2 : {img : "Zeus", name : "Zeus", atk : 7, hp : 12, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Thunderer's Wrath", style : "bolt", cost : 5, desc : "Deal 10 dmg to a mortal enemy",},
    god3 : {img : "Athena", name : "Athena", atk : 6, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Warrior Goddess", style : "passive", cost : 5, desc : "Every time Athena kills an enemy, she is healed by 2",},
    god4 : {img : "Poseidon", name : "Poseidon", atk : 6, hp : 12, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Earthquake", style : "bolt", cost : 5, desc : "Deal 1 damage to all enemies",},
    god5 : {img : "Hades", name : "Hades", atk : 5, hp : 12, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Lord of the Dead", style : "passive", cost : 5, desc : "On defeat, place the last two killed units in your army",},
    god6 : {img : "Hera", name : "Hera", atk : 4, hp : 12, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Queen of the Gods", style : "passive", cost : 5, desc : "Deal x2 dmg to heroes",},
    god7 : {img : "Ares", name : "Ares", atk : 4, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Thirst for War", style : "passive", cost : 5, desc : "When Ares' health is below 50%, he deals x2 dmg",},
    god8 : {img : "Aphrodite", name : "Aphrodite", atk : 4, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Divine Feminine", style : "passive", cost : 5, desc : "All female cards deal x2 dmg",},
    god9 : {img : "Apollo", name : "Apollo", atk : 5, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "God of Healing", style : "bolt", cost : 5, desc : "Heal 4 hp on an ally, all attacks are ranged",},
    god10 : {img : "Demeter", name : "Demeter", atk : 3, hp : 9, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Bountiful Harvest", style : "bolt", cost : 5, desc : "Draw a basic card and heal 4 hp on an ally",},
    god11 : {img : "Hermes", name : "Hermes", atk : 4, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Swift Footed", style : "passive", cost : 5, desc : "All Green cards deal +1 dmg",},
    god12 : {img : "Hephaestus", name : "Hephaestus", atk : 3, hp : 9, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Divine Engineering", style : "bolt", cost : 5, desc : "Stun 2 enemies and choose an ally to be taunted",},
    god13 : {img : "Artemis", name : "Artemis", atk : 5, hp : 10, connect : 4, red : 0, green : 0, blue : 0, type : "god", ability : "Goddess of the Hunt", style : "passive", cost : 5, desc : "All attacks are ranged, deal +2 dmg to monsters",},
// Monsters
    cyclopsMonster : {img : "Cyclops", name : "Cyclops", atk : 7, hp : 8, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "bolt", ability : "Devour", desc : "Eat a soldier",},
    minotaurMonster : {img : "Minotaur", name : "Minotaur", atk : 5, hp : 8, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "bolt", ability : "Savage Roar", desc : "Deal 1 dmg to all non-red cards in the enemy's army",},
    hydraMonster : {img : "Hydra", name : "Hydra", atk : 3, hp : 10, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "passive", ability : "Poisoned Blood", desc : "The killer of the Hydra takes 5 dmg",},
    medusaMonster : {img : "Medusa", name : "Medusa", atk : 4, hp : 9, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "passive", ability : "Stone Gaze", desc : "Any unit which attacks Medusa is stunned",},
    cretanBullMonster : {img : "CretanBull", name : "Cretan Bull", atk : 4, hp : 8, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "bolt", ability : "Charge", desc : "Can always attack first, first attack deals +2 dmg",},
    cerberusMonster : {img : "Cerberus", name : "Cerberus", atk : 5, hp : 10, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "bolt", ability : "Triple Threat", desc : "Attack your target 3 times",},
    chimeraMonster : {img : "Chimera", name : "Chimera", atk : 6, hp : 9, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "bolt", ability : "Breath Fire", desc : "Deal 2 dmg to connecting cards",},
    nemeanLionMonster : {img : "NemeanLion", name : "Nemean Lion", atk : 5, hp : 7, connect : 4, red : 0, green : 0, blue : 0, cost: 4, type : "monster", style : "passive", ability : "Thick Skinned", desc : "Reduces all incoming dmg by 1",},
};

module.exports.generals = [
    {img : "Agamemnon", name : "Agamemnon", atk : 2, hp : 10, connect : 4, red : 4, green : 0, blue : 0, type : "general", ability : "Leader of the Greeks", style : "passive", cost : 0, desc : "All soldiers deal +1 dmg",},
    {img : "Pericles", name : "Pericles", atk : 1, hp : 10, connect : 4, red : 0, green : 1, blue : 3, type : "general", ability : "Voice of Democracy", style : "passive", cost : 0, desc : "Connected soldiers deal +2 dmg",},
    {img : "Leonidas", name : "Leonidas", atk : 2, hp : 10, connect : 4, red : 3, green : 1, blue : 0, type : "general", ability : "Spartan Warcry", style : "passive", cost : 0, desc : "Leonidas must be killed first by the enemy",},
    {img : "Priam", name : "Priam", atk : 1, hp : 10, connect : 4, red : 1, green : 1, blue : 2, type : "general", ability : "Royal Wealth", style : "bolt", cost : 0, desc : "Draw 5 basic cards on your first turn",},
    {img : "Alexander", name : "Alexander", atk : 2, hp : 10, connect : 4, red : 0, green : 2, blue : 2, type : "general", ability : "Overwhelming Odds", style : "passive", cost : 0, desc : "The last unit in the army has x2 attack",},
    {img : "Dido", name : "Dido", atk : 2, hp : 10, connect : 4, red : 2, green : 0, blue : 2, type : "general", ability : "Ill-Fated Queen", style : "passive", cost : 0, desc : "On death, Dido's killer dies as well",},
    {img : "Cadmus", name : "Cadmus", atk : 2, hp : 10, connect : 4, red : 1, green : 2, blue : 1, type : "general", ability : "Founder's Spirit", style : "passive", cost : 0, desc : "When all connections are filled, deal x2 dmg",},
    {img : "Aeneas", name : "Aeneas", atk : 2, hp : 10, connect : 4, red : 2, green : 1, blue :1, type : "general", ability : "Divine Protection", style : "passive", cost : 0, desc : "The first unit to die is resurrected at half hp",},
];

// Taunt Token, Damage Tokens, Stun Tokens
